workflows:
  version: 2
  test:
    jobs:
      - test

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "./node_modules"
      - run: npm run build
      - run: npm run test-report
      - store_test_results:
          path: report.xml